### ISSUE TITLE
Full markdown with annotations

### ISSUE THREAD

**Issue by imagoiq** [lucasrla/remarks#10]
First of all, thanks for this great app ! I run it on WSL without any issue.

I didn't found a way to export all the text with highlights in Markdown, but only the highlighted parts. Is there such functionality ? Or is there a way to add it ?

**Comment by lucasrla** [comment]
Hey @imagoiq, 

It is good to know that remarks works smoothly on WSL. I added a mention to your confirmation to the [thread about setups](https://github.com/lucasrla/remarks/discussions/8).

Currently, remarks exports (to Markdown) only the text "around" the highlighted parts. I made it that way to fit my own needs.

PyMuPDF, the PDF library that we are using, does support plain text extraction ([see docs](https://pymupdf.readthedocs.io/en/latest/app2.html#plain-text)). So adding a new functionality in that vein is something (at least in principle) possible.

But could you please elaborate on what your needs are? 

It would be useful to understand more concretely what you are trying to achieve – before working on a new feature or recommending you potential alternatives.

Thanks

**Comment by imagoiq** [comment]
Thanks for your reply.

I'm a heavy user of Notions for all my personal notes or reading articles, and I'm looking for a workflow to synchronize those notes or articles with my Remarkable. Currently, there is an API in private beta for Notions (but I don't have access yet) so I'll need to wait a bit to fully make it functional.

I could use PDF which has the advantage to contain highlight but also scribble. But PDF in Notions (and probably most of the same kind of software) are "only" attached to a note/page and therefore it's a pain to navigate between multiple PDF and above all, it isn't indexed for search. So having a full markdown transcription with proper highlight could be good.

I'm still experimenting (and probably for a long time) how I can use my Remarkable in my everyday life so this is just and hypothetical idea.

**Comment by lucasrla** [comment]
I see, @imagoiq. Off the top of my head I have two recommendations (not specific to reMarkable). 

Given your workflow, these could be helpful:

- There is a neat tool that stores PDFs and also supports full-text search: [Raindrop.io](https://raindrop.io)

- If some of your PDF files are not searchable, I recommend testing out [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF). It inserts hidden searchable text beneath the existing content in a PDF (it does many other useful stuff as well)

I will go ahead and close this issue for now. Once you have more specific ideas, feel free to reopen this (or create a new one, whatever fits you better).

Thanks
