### ISSUE TITLE
Crop and split original PDF, then reconstruct it back as original, but with marks

### ISSUE THREAD

**Issue by akelai** [lucasrla/remarks#14]
remarks could enable a better workflow with reMarkable, if it could support this feature:
being able to "prepare" a PDF for the best reading and writing experience on a reMarkable in landscape mode (and reconstruct back with marks).

That would be achieved by cropping all margins (or only some of them) and splitting a page in two halves, so to have bigger font size on reMarkable in landscape mode. The two halves should have some overlap, so to avoid problems on the split edge. The cropping and splitting data should be inserted into the PDF metadata (because they will be needed for reconstruction).

The "prepared" PDF could be used on reMarkable normally, making marks (highlights, scribbles, annotations).

In order to get the PDF back in shape (but with marks), remarks should detect from metadata that the PDF had been "prepared", and create output PDF taking that metadata into account, thus reconstructing the original PDF as it was before cropping and splitting, and adding the marks made on reMarkable.

**Comment by lucasrla** [comment]
Hey @akelai, thank you for your suggestion.

Personally, I have never used my reMarkable on landscape. So my initial reaction is that this workflow with "preparation" and then "reconstruction" feels too specific.

If you are willing to code this feature, I could have a look at it and maybe merge it (or parts of it) into remarks.

In any case, remarks is free software, you can always fork it.

Thanks

**Comment by akelai** [comment]
Thanks!
