### ISSUE TITLE
Identifying a specific pdf when filename is uuid

### ISSUE THREAD

**Issue by jonwhittlestone** [lucasrla/remarks#17]
Hi

Great software/docs, it looks to be very promising.

However with my remarkable 2, I have downloaded the xochitl directory but can anyone suggest how to identify a specific pdf when all the filenames are uuids?

![image](https://user-images.githubusercontent.com/1681212/107012335-cef44a80-6790-11eb-98c4-e1da5d13aaf9.png)

**Comment by jonwhittlestone** [comment]
Ah, I can grep .metadata

```grep hastings *.metadata```

**Comment by lucasrla** [comment]
Nice that you have figured out a work around with `grep` on your own, @jonwhittlestone!

For anyone in a similar situations, try using `remark`'s flag `--pdf_name`, which acts like a filter.

One enters `python -m remarks [...] --pdf_name hastings` to work only on PDF files whose original names (visibleName) contain the string `hastings`.

Thanks
