### ISSUE TITLE
Only top layer of annotations exported

### ISSUE THREAD

**Issue by thamnos** [lucasrla/remarks#26]
Hi! When I use several layers on the remarkable to write my annotations on, only the top layer seems to be handled by remarks. So If I added a second layer, only the contents of Layer 2 will be visible in the exported pdf.

**Comment by lucasrla** [comment]
Hey @thamnos, 

Whenever I write/draw in two different layers on my device, I have always been able to extract the content from both layers later on. So I am yet to notice any issue related to multiple layers and `remarks`.

In order for me to reproduce your issue, can you please share the PDF and the internal files (from the `xochitl` directory) here?

Thanks
