### ISSUE TITLE
[Feature Request] Maintain directory structure

### ISSUE THREAD

**Issue by folofjc** [lucasrla/remarks#3]
In the output directory, would be great if it maintained the same directory structure as on the reMarkable. I have a lot of pdfs and have them organized, so the output directory gets a bit cluttered.

**Comment by lucasrla** [comment]
That would be nice indeed!

It should be easy to parse the `parent` key in .metadata files and then reuse the device's directory structure.

I will look into that by the weekend. But if you have the time and want it sooner, I am happy to review and approve any PRs.

**Comment by folofjc** [comment]
Great, thanks! I'll see what I can do ;)

**Comment by folofjc** [comment]
@lucasrla I made the change and it works for me. I tried to push a new branch and it said that I did not have permission. I also merged it into my local master and tried to push that, also said that permission was denied. 

Since I cannot push the branch, I cannot create a PR.

**Comment by lucasrla** [comment]
Thank you for your contribution, @folofjc! It is now merged into master, see #5 

I took the liberty of doing a few amendments to your PR to make it more in line with the existing codebase.
