### ISSUE TITLE
Upgrade to rM v2.11

### ISSUE THREAD

**Issue by folofjc** [lucasrla/remarks#39]
In my previous issue #37, I noted that the rM software will "snap" to text, and therefore make a new type of highlight. At the time, rM made each line a new highlight rectangle. Therefore, when I fixed this in PR #38, I assumed that there was one rectangle per highlight. 

In rM v2.11, this is no longer true. You can highlight multiple lines or even a whole paragraph. Therefore there are multiple rectangles per highlight. Therefore I need to fix this. I will branch off my previous pull request.

**Comment by folofjc** [comment]
This should still be fixed in PR #38

**Comment by allispaul** [comment]
Version 2.11 also introduced green and pink colors for the highlighter, and blue and red colors for the pen tools. Could remarks also handle these? Currently the highlighter colors are all showing up as yellow, and the blue and red pen colors are throwing a KeyError.

**Comment by folofjc** [comment]
Ah, good point. I hadn't tested that. I might be able to try to fix that in my PR. RIght now the colors are indeed hard coded for the highlighter.

**Comment by haaase** [comment]
Hi, I added support for highlighter colours in #44. I did not test the new pen colours yet but support should be trivial to implement.

**Comment by folofjc** [comment]
Hey @lucasrla sorry, I am out of town. I was going to do this when I get back. But I guess you already figured it out? All you have to do is highlight a whole paragraph by swiping downward along the left edge of a paragraph.

**Comment by lucasrla** [comment]
Yes, nevermind the example of overlapping highlights. I was able to reproduce it myself. Thanks!
