### ISSUE TITLE
Add support for converting PDFs to Remarkable bundles

### ISSUE THREAD

**Issue by apoorvkh** [lucasrla/remarks#51]
I am very interested in having a program that converts your PDF and annotations into the remarkable bundle format. I believe a solution exists for PDFs to RM, but none that supports annotations. In fact, something with this capability (being able to convert a "remarkable bundle" into a PDF and PDF to "remarkable bundle") would create the possibility for having bidirectional syncing, which would be very useful.

For this case, one must use the same annotation formats (and PDF parser) for both types of conversions. Then, we would be able to make comparisons between annotated files. I propose the following:

RM to PDF:
- Convert remarkable bundles to PDFs as you do now (`*.rm` files become scribbles/highlights, which overlay the stored PDF file)

PDF to RM:
- Extract any PyMuPDF-compatible scribbles or highlights as `.rm` files. Ignore any annotations that would not be considered "scribbles" or "highlights" by the remarkable.
- Remove the extracted annotations and create an updated PDF file (which might still include ignored annotations in the above step).
- Then, the remarkable bundle will include the `.rm` files and updated PDF file.

I think this an important feature to have and would help make the open-source remarkable pipeline more feature-complete. Hopefully, this approach could be a decent starting point. I think remarks is the best "RM to PDF" codebase and, as you are most familiar with it, it would be fantastic if you could consider adding support for this or letting me know your thoughts. Thanks so much for your consideration!

**Comment by lucasrla** [comment]
Interesting idea. Couple of quick thoughts:

1. You haven't listed them explicitly but the JSON-based "smart" highlights might be the easiest way to starting building the PDF-to-bundle part. Those JSON files seem easy to create from scratch. Personally, I sometimes highlight PDFs on macOS Preview, so I could see the value of having my Preview highlights also available within the reMarkable tablet.

2. To remarks users (current or future), apart from the reMarkable device, what are the other relevant ways they draw scribbles on documents? Would it be drawing with a mouse on something like macOS Preview (or Adobe Acrobat)? Maybe something with iPad + Apple Pencil? Knowing more about the nature of the scribbles to be written to RM files (and having actual examples to compare against) would be very helpful to define the scope of such a feature.

3. The parsing and drawing parts of the remarks' codebase are messy. They were the very first parts that I quickly put together (and I haven't touched them in years)... They would certainly need some love (a complete rewrite?!) if we were to extend/build upon them.

In any case, happy to consider PRs related to your idea. Just let us know what you think!

Thanks
