### ISSUE TITLE
Multiple, wrong highlights in certain edge cases

### ISSUE THREAD

**Issue by opal06** [lucasrla/remarks#57]
What I mean by this are highlight patterns like seen in this image:
![Bildschirmfoto vom 2023-02-09 14-28-48](https://user-images.githubusercontent.com/41026414/217827705-835b489e-7696-4dfa-bfb9-f2e33237bc44.png)

I have come across this same issue when working on [zotero2remarkable_bridge](https://github.com/opal06/zotero2remarkable_bridge) and it seems we are using very similar approaches for highlight generation: Use pymupdf's search feature to find the extracted text from the .highlights file and then create an annotation based on the quads from this search. Now the issue comes from the fact that if pymupdf finds multiple occurenses of the same string, it returns all of them. So generating highlights based off of these quads will generate highlights on all occurenses.  Most of the time strings are sufficiently unique for this to not be an issue, but edge cases exist. In the picture above for example in the first column I highlighted the phrase "recent research indicates ...", but as "recent" was broken over to lines, reMarkable created to hightlights, one with text "re" and another with text "cent research ...". "re" was than found all over the text because it is such a common sequence of letters.

I must admit that I have never come around to find a solution for this problem for my own program, which is why I would like to see if we could come up with a solution together. My line of thinking for now always was that one could probably use the "rect" or "start" and "length" data from the .highlights file to find the correct sequence in case of more then one result, but I could never get it to work...

**Comment by lucasrla** [comment]
Ouch! To make it easier investigating this edge case, would you mind sharing the raw files here? I'll check them to see if I can come up something...

**Comment by lucasrla** [comment]
One thing that has just occurred to me is the `clip` parameter available in `search_for` since PyMuPDF 1.18.2. Have you tried it? 

Maybe the `rects` from the .highlights file could be used to set the boundaries for the clipping area?

From the [official docs](https://pymupdf.readthedocs.io/en/1.21/page.html#Page.search_for):

```python
search_for(needle, *, clip=clip, quads=False, flags=TEXT_DEHYPHENATE | TEXT_PRESERVE_WHITESPACE | TEXT_PRESERVE_LIGATURES, textpage=None)

  clip (rect_like) – (New in v1.18.2) only search within this area.
```

**Comment by opal06** [comment]
> Ouch! To make it easier investigating this edge case, would you mind sharing the raw files here? I'll check them to see if I can come up something...
Here is the zip of the raw files as downloaded by rmapi. 
[Kayseri Ausschnitt.zip](https://github.com/lucasrla/remarks/files/10902776/Kayseri.Ausschnitt.zip)



> One thing that has just occurred to me is the `clip` parameter available in `search_for` since PyMuPDF 1.18.2. Have you tried it?
> 
> Maybe the `rects` from the .highlights file could be used to set the boundaries for the clipping area?
> 
> From the [official docs](https://pymupdf.readthedocs.io/en/1.21/page.html#Page.search_for):
> 
> ```python
> search_for(needle, *, clip=clip, quads=False, flags=TEXT_DEHYPHENATE | TEXT_PRESERVE_WHITESPACE | TEXT_PRESERVE_LIGATURES, textpage=None)
> 
>   clip (rect_like) – (New in v1.18.2) only search within this area.
> ```

Honestly, no. I had played around with the rects previously before going the `search_for` route, but got frustrated with the scaling, which I couldn't get to work. Others (including you?) have figured it out though, so that could work...

**Comment by lucasrla** [comment]
Thanks for the raw files. I'll have a look at them in the upcoming days.

Incidentally, Daniel posts on [issue #52](https://github.com/lucasrla/remarks/issues/52) hint at how to map .highlights coordinates to/from PyMuPDF bboxes. That might be the answer to scaling that you were looking for!

**Comment by lucasrla** [comment]
Hey @opal06, could you please test the latest commit ([55eb1ad](https://github.com/lucasrla/remarks/commit/12e1bde4265cc5254a14e814f9a4af4269e6ea3d))? 

As far as I can tell, your issue and Daniel's are now solved!

**Comment by opal06** [comment]
Yes, it is fixed! Great work!
