### ISSUE TITLE
Will the code work for ipad annotated pdfs as well? 

### ISSUE THREAD

**Issue by dummifiedme** [lucasrla/remarks#9]
I am interested in taking out highlights and associated comments as markdown or even text. If the drawn annotations are also captured its a bonus

**Comment by dummifiedme** [comment]
I guess, it won't. Nevermind.

**Comment by lucasrla** [comment]
As you have already realized, `remarks` won't work with the iPad. It has been built specifically with [reMarkable tablets](http://remarkable.com) in mind.

I hope you will be able to find an iPad app that suits your needs... Unfortunately I am not a user and cannot help with suggestions.

**Comment by dummifiedme** [comment]
sure, thanks :)
